### ISSUE TITLE
Missing error state during SSR

### ISSUE THREAD

**Issue by basharh** [lfades/next-with-apollo#112]
Is there a way to be informed of Graphql errors during SSR through the react hooks. The `useQuery` hook currently does not return error state during SSR on the server. My goal is basically to render the error UI on the server without waiting for the client to make the call again. 

I can look further into the `next-with-apollo` code but I was wondering if there's already a way to do it or if it's in the plan. Is it even architecturally feasible for `next-with-apollo` to inform every apollo hook of errors in their particular queries during SSR?

**Comment by lfades** [comment]
Have you tried using the error middlewares provided by Apollo? (apollo-link-error)

**Comment by miracle2k** [comment]
Ran into this issue in a non-next app. You can run the query with ``errorPolicy: all``, and you `useQuery()` should receive the partial data of the query, the part which did not error - however, the ``error`` itself will be lost.

I think fundamentally the problem is that the query-pass is just a tree render + make a copy of the apollo cache. It then "communicates" the outcome of the querying to the SSR render-pass (and than the browser rehydrate) by sending along the full cache. The errors are just not a part of that.

For me, I've come to the conclusion that this is a fundamental design flaw with the `getDataFromTree` approach (which already has other issues, such as requiring an extra render), and I will move to doing a manual root-level query at the `getInitialProps` level.
