### ISSUE TITLE
Typings for `client` object are incorrect

### ISSUE THREAD

**Issue by SpaceK33z** [lfades/next-with-apollo#12]
In the readme, it says you can do this:

```js
withApollo({
  client: () => ({
    cache: new InMemoryCache()
  }),
  link: {
    http: new HttpLink({
      uri: GRAPHQL_URL
    })
  }
})
```

And this works correctly, except that TypeScript gives the error: `Property 'link' is missing in type '{ cache: InMemoryCache; }'`.

I haven't made a PR yet because I don't know if the docs should be updated, or the types should be updated (and if so, how, since they just [use the `ApolloClient` types](https://github.com/lfades/next-with-apollo/blob/fcf657e7fe710193ff644494849af30c763303dd/src/types.ts#L28)).

**Comment by lfades** [comment]
Right, you may want to do this:

```ts
withApollo({
  client: ({ link }) => ({
    link: link as ApolloLink,
    cache: new InMemoryCache()
  }),
  link: {
    http: new HttpLink({
      uri: GRAPHQL_URL
    })
  }
})
```

Two things to notice:

First that I'm adding `link`, I'm already doing that by default but `ApolloClientOptions` requires `link` to be present, I don't know what to do there actually, I don't want to clone  `ApolloClientOptions` but I want to use it, so it gives proper type checking.

Second that I'm using `link as ApolloLink`, that's because of this: `{ headers?: IncomingHttpHeaders; link?: ApolloLink }`, `link?` is undefined when you're returning an `ApolloClient` directly and not using the custom `link` (the one that has http, ws, setContext), but in this case it's always defined.

If you know how can I improve the types, specially for the second part, it would be awesome 👍

**Comment by lfades** [comment]
I created a new branch [v2.2](https://github.com/lfades/next-with-apollo/tree/v2.2) that fixes this issues by accepting an `ApolloClient` directly into `withApollo` or a function that returns an `ApolloClient` or (this case) an object that uses `client` and `link` to build the `ApolloClient`, it's backwards compatible unless you're using typescript, let me know what you think, and if it should be a 3.0 instead

**Comment by SpaceK33z** [comment]
Thanks so much! Yeah I guess this would be a v3 since it is breaking?
