### ISSUE TITLE
url prop not immediately available

### ISSUE THREAD

**Issue by f2net** [lfades/next-with-apollo#17]
# Intro
With next.js 6, with a custom _app.js, you have to add the following code to have the url prop available to components (see https://github.com/zeit/next.js/issues/4284):

```javascript
import React from 'react';
import App, { Container } from 'next/app';

export default class MyApp extends App {

  static async getInitialProps({ Component, ctx }) {
    let pageProps = {};

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx);
    }

    return { pageProps };
  }

  createUrl = (router) => {
    // This is to make sure we don't references the router object at call time
    const { pathname, asPath, query } = router;
    return {
      get query() {
        return query;
      },
      get pathname() {
        return pathname;
      },
      get asPath() {
        return asPath;
      },
      back: () => {
        router.back();
      },
      push: (url, as) => router.push(url, as),
      pushTo: (href, as) => {
        const pushRoute = as ? href : null;
        const pushUrl = as || href;

        return router.push(pushRoute, pushUrl);
      },
      replace: (url, as) => router.replace(url, as),
      replaceTo: (href, as) => {
        const replaceRoute = as ? href : null;
        const replaceUrl = as || href;

        return router.replace(replaceRoute, replaceUrl);
      },
    };
  }

  render() {
    const { Component, pageProps, router } = this.props;
    const url = this.createUrl(router);
    return (
      <Container>
        <Component {...pageProps} url={url} />
      </Container>);
  }

}
```

# The problem

Now, the problem is that, using next-with-apollo this url property is not immediately available when you use it as a query parameter, in a "old-fashioned" HOC graphql()

```javascript
graphql(getCategory, {
  options: ({ url }) => ({
    variables: { seoName: url.query.seoName }
  })
})
```

It is immediately available only if I modify the withApollo code to spread on the <App> component also a url prop created in this way:

```javascript
const url = {
  pathname: appCtx.router.pathname,
  query: appCtx.router.query
}
```

Otherwise I have to skip the query when url is not available to avoid GraphQL errors.

Is it an issue? If not, what would you suggest?

Thank you,
Matteo

**Comment by lfades** [comment]
Hi @f2net, Here are some solutions:

Use `withRouter` instead of the `url` prop, it's better this way and that's why `url` was deprecated.

If the above is not possible at the moment then you need to send a minimal version of the `url` in your _app's `getInitialProps`, I'm using `getDataFromTree` to get the `initialState`, this first operation on the first render runs inside `getInitialProps`, the browser is not yet there and your component is not really being rendered, I'm just querying all the queries required by the page, which means you only need to send something like:
```js
url: { query, pathname, asPath }
```
To make your queries run on SSR, and then use `createUrl` from there 💯

**Comment by lfades** [comment]
@f2net can we close this issue now ?
