### ISSUE TITLE
Type 'DefaultClient<any>' is not assignable to type 'ApolloClient<any>'.

### ISSUE THREAD

**Issue by serranoarevalo** [lfades/next-with-apollo#22]
I'm getting this error after following the example with Typescript:

<img width="656" alt="screen shot 2018-08-30 at 11 38 52 am 1" src="https://user-images.githubusercontent.com/3612017/44840309-70365880-ac49-11e8-9e67-cec92de8cd45.png">

Next is compiling and working so looks like is only a typing error?

**Comment by lfades** [comment]
Mmm can you show me what's below of "They have separate declarations of a private property 'cache'" ?

**Comment by serranoarevalo** [comment]
That's all it says, there is nothing below.

This my tsconfig: 
https://github.com/serranoarevalo/indie-makers-client/blob/master/tsconfig.json

and this is the tslint:
https://github.com/serranoarevalo/indie-makers-client/blob/master/tslint.json

Nextjs config:

https://github.com/serranoarevalo/indie-makers-client/blob/master/next.config.js

**Comment by lfades** [comment]
From my point of view [this client](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-boost/src/index.ts#L54) should be compatible with [this other client](https://github.com/lfades/next-with-apollo/blob/82c1938f59cf3d16814c60c68963ff3343703f5f/src/types.ts#L34). Maybe the types of my version of `apollo-client` are outdated, otherwise I'm really not sure and I currently don't have a project to use as an example 🙁

**Comment by lfades** [comment]
Maybe a direct solution is just to update the dependencies of the package, I'm only including `apollo-client` for the types, nothing else, do you want to do a PR ?

**Comment by serranoarevalo** [comment]
I will update the types when I'm on my laptop and if it solves the problem I will make PR :)

**Comment by serranoarevalo** [comment]
https://github.com/lfades/next-with-apollo/pull/24
