### ISSUE TITLE
Cookies not being sent.

### ISSUE THREAD

**Issue by serranoarevalo** [lfades/next-with-apollo#26]
I can't seem to get cookies to work with this HOC, I need to send the cookies to the server (on the same domain) both in SSR and CSR  for authentication porpuses but is just not working. Have you implemented any authentication flow with this HOC? Am I missing something? I created both a client with Apollo boost and manually as well but still is not working.

**Comment by lfades** [comment]
To send cookies in the browser you need to use [credentials](https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials).

To send cookies in SSR you need to send the cookies inside the `headers` of the request, there's no browser instance in SSR so credentials does nothing in this case.

Usage example:
```js
import withApollo from 'next-with-apollo';
import ApolloClient from 'apollo-boost';

export default withApollo(
  ({ headers }) =>
    new ApolloClient({
      uri: process.API_URL,
      credentials: 'include',
      headers
    })
);
```

I'm going to close this issue now, if you keep having the issue, feel free to comment.

**Comment by HeyHugo** [comment]
Hi, I'm trying to get authentication with session cookie working with SSR. But for me `headers` in your example is `undefined` here.  When replacing `{ headers }` with `props` and logging it, it says:
 `{ initialState: {} }`

My setup is according to  the docs otherwise

**Comment by lfades** [comment]
@HeyHugo That's because it's not possible, for the browser always use the credentials option or manually create the headers. Sending the headers to the client will be a security issue, because headers may contain `http` only cookies or other sensitive information. Same thing with `ctx`, it contains SSR stuff that's never available in the browser, like access to the request and response.

**Comment by serranoarevalo** [comment]
@HeyHugo Maybe what you need is what I needed when I asked this question.

Are you trying to share credentials between the API and the NextJS page?

**Comment by HeyHugo** [comment]
@lfades Hmm not sure I follow. The session cookie  **is** a httpOnly coookie (since it's for a session).

The logging I did is on the nextjs server side not in the browser. Also if I log the `req.headers` in `getInitialProps` I can see the session cookie that I want to "reuse".

Maybe what I'm trying to achieve is not possible without using a token based authentication without httpOnly cookie?

@serranoarevalo Yes sounds right. When my browser has an authenticated httpOnly session cookie I wan't that same cookie to be used by nextjs server when it's calling my API doing SSR.

**Comment by lfades** [comment]
@HeyHugo Yes, you can see the cookies in the headers during SSR, but in the browser that information is secret and it's treat in a different way, that's why we have [credentials](https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials). In my example you can see that I'm sending the headers, which does the job of sending the cookies and other headers during SSR, then in the browser `headers` is `undefined` but now it's using `credentials: include`, which will send the cookies too.

**Comment by HeyHugo** [comment]
Well my problem is that headers are not visible in SSR on server. I know it should not be visible on the client side.

(A) Browser --->  (B) next SSR ---> (C) API

1. (A) Browser has a session (httpOnly cookie) 
2. (A) It requests a page to be rendered by next SSR. Since B and C share domain and 
`credentials` option is set to 'include' the session cookie should follow right?
3. **(B) During rendering some component renders an Apollo query. `withApollo` is run but `headers` prop is not injected in args.**
4. (C) API request fails since it was not authorised and the cookie was not in the headers.

**Comment by lfades** [comment]
@HeyHugo `credentials` does nothing in SSR because there is no browser instance.

**Comment by HeyHugo** [comment]
Ahh it's finally working 😅 .. my problem was this:

I imported ApolloClient like this:
`import {ApolloClient} from 'apollo-boost'` 
instead of 
`import ApolloClient from 'apollo-boost'`
using ApolloClient now gave error if I did not set `link` and `cache` options as well

So ApolloClient was created like this:
```javascript
...
return new ApolloClient({
    link: new HttpLink({
        uri: `my-api-host/graphql`, 
        credentials: 'include', 
    }),
    ssrMode: true,
    headers: headers
})
```
..credentials was put in HttpLink instead of ApolloClient. I think was the API for Apollo in a previous version.

Anyways thanks @lfades for having patience with me, this package is gold if you want apollo in combination with nextjs :)
