### ISSUE TITLE
Question: why is initialState running on server side?

### ISSUE THREAD

**Issue by remy** [lfades/next-with-apollo#35]
When I do a hard refresh, and add a `console.log` in my `createClient` function, I can see that the first call includes the `headers` but there's a second call that _only_ has `initialState` - which means somewhere the apollo client is being returned with no headers attached - which, I'm guessing means it'll fail auth'ed requests?

I'm using next-with-apollo@3.3.0.

**Comment by lfades** [comment]
That's the intended behavior, the first time the Apollo client is being created in the server (SSR), that's why you have access to `headers` (from `req.headers`), but the second time it's created in the browser, and there `headers` don't exist because you no longer have access to the request, but you do have access to `initialState`, which is the state created by the Apollo client in the server.

related to #26

**Comment by remy** [comment]
I think you missed what I was saying. There's a second call *on the server* that only has `initialState`.

**Comment by lfades** [comment]
Oh sorry, it should be ran only once in the server, do you see it twice ? and does `initialState` have any content ?

**Comment by remy** [comment]
No, `initialState` is empty.

I'm just wondering if it's worth trying a console trace to see where it's
coming from, but suspect it'll be mostly internal webpack gumph.

**Comment by xiaoyu-tamu** [comment]
I am wondering why we don't get ctx when call on the server?


```
export default withApollo(({ ctx, initialState }) => {
  console.log('ctx type: ', typeof ctx);
  console.log('is server', typeof window === 'undefined');
  console.log('is browser', typeof window !== 'undefined');
  return new ApolloClient({
    uri: process.env.GQL_ENDPOINT,
  });
```

On the server, this will print

ctx type:  object
is server true
is browser false

ctx type:  undefined
is server true
is browser false

**Comment by lfades** [comment]
@xiaoyu-tamu Huh, that's weird, do you have a repo to which I can take a look ?

**Comment by xiaoyu-tamu** [comment]
I just made one. https://codesandbox.io/s/zlppn12mvm



![image](https://user-images.githubusercontent.com/33362998/50056175-34eb6700-011e-11e9-9d15-3eb2f3012f80.png)

**Comment by lfades** [comment]
Thank you for the reproduction!, I'll take a look into it soon 💃

**Comment by lfades** [comment]
@xiaoyu-tamu Thank you so much, I'll see how to fix it ASAP 🙏 .

**Comment by xiaoyu-tamu** [comment]
@lfades Thank you!

**Comment by lfades** [comment]
I just checked and this is the intended behavior, the first time it's run to get all query's data, and for that task a `ApolloServer` instance is necessary, the second time it's for the render in the server, and only `initialState` will be available, I'll do an update to the readme to make this more clear.

As a side note, in the future this will no longer be an issue because `getDataFromTree` will be replaced by React Suspense.

Thank you guys 👍

**Comment by xiaoyu-tamu** [comment]
Cool! Looking forward to the new great things :)
