### ISSUE TITLE
How to handle multi

### ISSUE THREAD

**Issue by junaid33** [lfades/next-with-apollo#51]
I have a backend GraphQL server but also want to connect with a 3rd party GraphQL API. How should we handle multiple Apollo clients? Should we wrap the HOC twice?

**Comment by lfades** [comment]
I don't think that it's recommended to have multiple Apollo Clients, what's your use case and why do you need multiple clients ?, - There may be a solution but it will not look good.

**Comment by lfades** [comment]
Okay, but do you understand that Apollo Devtools may not work, you will have multiple caches, and also that SSR will be much harder ? specially because you'll need to specify the Apollo client to use per query (And I'm not sure if SSR will work for that).

A better solution can be to merge your schema with Shopify's one using [schema stitching](https://www.apollographql.com/docs/graphql-tools/schema-stitching.html), one of the principles of GraphQL is to have one single source of truth, so it does make more sense.

**Comment by junaid33** [comment]
Yes I looked into schema stitching, but I will look for another solution. Thank you for your help.
