### ISSUE TITLE
[with-sentry] Can't catch error in _app.jsx

### ISSUE THREAD

**Issue by HeadFox** [lfades/next-with-apollo#52]
Hi :)
I tried to integrate sentry in my nextjs project with the official with-sentry example in nextjs repo. But in production errors are not catch. I investigate a little bit and I found that withApollo catch all errors before rendering _app.jsx. And so I can't catch errors in my app.jsx getInitialProps. So I tried to catch the error inside the withApollo try/catch and it works !
But it's not a solution to catch error like this ! Do you have a solution to only catch error in _app.jsx ?
And by the way all errors in dev mod are logs as GraphQL errors because of that `console.error('GraphQL error occurred [getDataFromTree]', error);`

**Comment by lfades** [comment]
Those logs are intentional, that way we can fix found bugs in dev mode, that try and catch is only for SSR and only to get the initial data from the queries, it does not handle the render of `_app.js`, that's going to happen outside of that try and catch so you should not have any problems handling those.

**Comment by HeadFox** [comment]
I found a temporary fix, in my try I test if ctx contains err and then I capture the exception with sentry.
` if (ctx.err) {
        captureException(ctx.err, ctx);
      }`

I can only catch SSR exception that way.  Maybe the problem comes from the with-sentry examples.
But because next-with-apollo is an HOC of my _app.jsx I thought it was the problem.
