### ISSUE TITLE
Question about ctx.res.headersSent and ctx.res.finished

### ISSUE THREAD

**Issue by isBatak** [lfades/next-with-apollo#61]
Could someone explain what is the purpose of this if statement? https://github.com/lfades/next-with-apollo/blob/edb04a8cedf328d462b5d81c8d740e85ced73ab1/src/withApollo.tsx#L58

**Comment by lfades** [comment]
@isBatak Before that line I call the `getInitialProps` from `App`, that one also calls the `getInitialProps` from the page, and inside that `getInitialProps` you get access to the `request` and `response`, a user may end the request before a render and if that's the case then we don't have todo anything else because the request has already finished.

**Comment by isBatak** [comment]
@lfades thx for the clarification :)
