### ISSUE TITLE
Automatic Partial Static Export

### ISSUE THREAD

**Issue by NikoMontana** [lfades/next-with-apollo#73]
With `v.9` we got this cool thing called "Automatic Partial Static Export" with the indicator icon in the bottom right corner. So I know if this will be a prerendered page or not. 

Just want to get my head around this case, why do we lose this icon when we are using this lib? Is it because `getInitialProps` is called in the root which is blocking all sites from the static export abillity?

In my case I also have some landingpages which are not connected to my API which again I would like to serve static and save ressources. So this repo might not be the ideal solution for this case? Any advices?

**Comment by lfades** [comment]
> Just want to get my head around this case, why do we lose this icon when we are using this lib? Is it because getInitialProps is called in the root which is blocking all sites from the static export abillity?

Yes, you got it there, this is something that I've been also thinking about, Apollo uses a shared cache, so you need to have it in a place where it doesn't get destroyed and can be shared between pages, the only place for it is then `_app`. You can't prerender any page because this lib (and every other Apollo implementation I've seen) will add `getInitialProps` to `_app`, this is needed because `getInitialProps` is the way we can get SSR in pages.

There are 2 ways of solving it, the first and most simple one is removing `getInitialProps` and only handle the Apollo client in the page, this way every page can even be static, the downside is that none of the pages will have `SSR` for queries.

The other solution is the same first solution, but now also letting every page decide if it wants to have SSR or not by adding `getInitialProps` to the page (or maybe some config or something like that), but that would of course be a breaking change

**Comment by NikoMontana** [comment]
Thank you @lfades for helping me out to understand this topic! 

In addition to your explaination and the fact that apollo needs a shared cache [this lib](https://github.com/adamsoffer/next-apollo-example) would be nonsence, because every page is initializing the apollo client and destroying the previous cache?

> The other solution is the same first solution, but now also letting every page decide if it wants to have SSR or not by adding getInitialProps to the page (or maybe some config or something like that), but that would of course be a breaking change

Well, maybe v.10 will make that happen. Until then I will go with pure SSR for all pages.

**Comment by lfades** [comment]
@NikoMontana I did some research in a test project and I think it can work out outside of `_app` and still have a shared cache without issues, it would not have to be a breaking change so I'll see how to add it soon 👍

**Comment by mariohoyos92** [comment]
Would also love ability to use this with page components :) Thanks for all you do @lfades and viva Colombia!

**Comment by Emiliano-Bucci** [comment]
Hello! Is there any news on this? Do we still have to wrapp our main app? Thanks! :)

**Comment by DoWhileGeek** [comment]
Also wondering if theres been any new developments on this.

**Comment by lfades** [comment]
I've added this to my todos and I'll try to address it next week, I'm sorry for the delay, I just need to get time to do it 👷

**Comment by raajnadar** [comment]
@lfades did you find any solution?
